name: Deploy Webpage
on: workflow_dispatch

jobs:

  build_webgl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: prepare
        run:  |
          sudo apt update
          sudo apt install webp
          python3 fips emsdk install latest
      - name: build
        run: |
          python3 fips set local on
          python3 fips webpage build webgl
      - name: upload-artifact
        uses: actions/upload-artifact@main
        with:
          name: webpage_webgl
          path: fips-files/deploy/sokol-webpage-webgl
          retention-days: 1

  build_webgpu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: prepare
        run:  |
          sudo apt update
          sudo apt install webp
          python3 fips emsdk install latest
      - name: build
        run: |
          python3 fips set local on
          python3 fips webpage build webgpu
      - name: upload-artifact
        uses: actions/upload-artifact@main
        with:
          name: webpage_webgpu
          path: fips-files/deploy/sokol-webpage-webgpu
          retention-days: 1

  deploy_webgl:
    needs: build_webgl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          repository: floooh/sokol-html5
          ssh-key: ${{ secrets.SOKOL_HTML5_DEPLOY }}
      - uses: actions/download-artifact@main
        with:
          name: webpage_webgl
      - name: "commit and push"
        run: |
          git config user.email "none"
          git config user.name "GH Action"
          git add .
          git commit -m "updated (${{ github.run_number }})"
          git push

  deploy_webgpu:
    needs: build_webgpu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          repository: floooh/sokol-webgpu
          ssh-key: ${{ secrets.SOKOL_WEBGPU_DEPLOY }}
      - uses: actions/download-artifact@main
        with:
          name: webpage_webgpu
      - name: "commit and push"
        run: |
          git config user.email "none"
          git config user.name "GH Action"
          git add .
          git commit -m "updated (${{ github.run_number }})"
          git push
